/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewXMLToolParameterDialog.java
 *
 * Created on Sep 1, 2010, 2:52:32 PM
 */

package savant.view.dialog;

import savant.tools.program.ProgramArgument;
import savant.tools.program.ProgramArgument.Requirement;
import savant.tools.program.ProgramArgument.Type;

/**
 *
 * @author mfiume
 */
public class NewXMLToolParameterDialog extends javax.swing.JDialog {

    private boolean dialogComplete = false;
    private ProgramArgument argument = null;

    public boolean didDialogComplete() {
        return dialogComplete;
    }

     public ProgramArgument getProgramArgument() {
        if (this.dialogComplete) {
            if (createProgramArgument()) {
                return argument;
            }
        }
        return null;
    }

    private boolean createProgramArgument() {
        if (argument != null) { return true; }

        Type t = savant.tools.program.ProgramArgument.Type.valueOf(this.dd_type.getSelectedItem().toString());
        Object v = null;
        String initvalstr = this.txt_default.getText();
        switch(t) {
            case String:
                v = initvalstr;
                break;
            default:
                System.err.println("Not implemented for type " + t);
                return false;
        }

        argument = new ProgramArgument(
                this.txt_name.getText(),
                this.txta_description.getText(),
                this.txt_flag.getText(),
                this.txt_category.getText(),
                v,
                (this.dd_required.getSelectedItem().toString().equals("Yes") ? Requirement.Mandatory : Requirement.Optional),
                (this.dd_required.getSelectedItem().toString().equals("Yes") ? true : false),
                t
                );

        return true;
    }

    /** Creates new form NewXMLToolParameterDialog */
    public NewXMLToolParameterDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_flag = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_description = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txt_category = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dd_type = new javax.swing.JComboBox();
        dd_io = new javax.swing.JComboBox();
        dd_required = new javax.swing.JComboBox();
        dd_editable = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txt_default = new javax.swing.JTextField();
        butt_cancel = new javax.swing.JButton();
        butt_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Tool Parameter");

        jLabel1.setText("Parameter Information");

        jLabel2.setText("Flag:");

        jLabel5.setText("Description:");

        txta_description.setColumns(20);
        txta_description.setRows(5);
        jScrollPane1.setViewportView(txta_description);

        jLabel4.setText("Category:");

        jLabel6.setText("IO:");

        jLabel7.setText("Editable:");

        jLabel8.setText("Required:");

        jLabel3.setText("Name:");

        jLabel9.setText("Type:");

        dd_io.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Input", "Output" }));

        dd_required.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));

        dd_editable.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));

        jLabel10.setText("Default:");

        butt_cancel.setText("Cancel");

        butt_ok.setText("OK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(340, 340, 340))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)
                                .addComponent(jLabel9)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)
                                .addComponent(jLabel3))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                .addComponent(dd_type, javax.swing.GroupLayout.Alignment.LEADING, 0, 372, Short.MAX_VALUE)
                                .addComponent(txt_category, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                .addComponent(txt_flag, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                .addComponent(dd_io, javax.swing.GroupLayout.Alignment.LEADING, 0, 372, Short.MAX_VALUE)
                                .addComponent(dd_required, 0, 372, Short.MAX_VALUE)
                                .addComponent(dd_editable, javax.swing.GroupLayout.Alignment.LEADING, 0, 372, Short.MAX_VALUE)
                                .addComponent(txt_default, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(butt_ok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butt_cancel)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_flag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dd_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dd_io, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dd_required, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dd_editable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_default, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butt_cancel)
                    .addComponent(butt_ok))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butt_cancel;
    private javax.swing.JButton butt_ok;
    private javax.swing.JComboBox dd_editable;
    private javax.swing.JComboBox dd_io;
    private javax.swing.JComboBox dd_required;
    private javax.swing.JComboBox dd_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_category;
    private javax.swing.JTextField txt_default;
    private javax.swing.JTextField txt_flag;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextArea txta_description;
    // End of variables declaration//GEN-END:variables

}
