/*
 *    Copyright 2011 University of Toronto
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package savant.view.swing.start;

import java.awt.*;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;

/**
 * Sub-panel within the StartPanel.
 *
 * @author mfiume
 */
public class StartSubPanel extends JPanel {

    StartSubPanel(String title, JComponent body) {
         initComponents();
         init(title, body);
    }

    @Override
    protected void paintComponent(Graphics g) {

        int x = 2;
        int y = 2;
        int w = getWidth() - 4;
        int h = getHeight() - 4;
        int arc = 30;

        Graphics2D g2 = (Graphics2D)g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        GradientPaint gradient = new GradientPaint(x, y-40, StartPanel.SUBPANEL_TOP_BACKGROUND_COLOR, x, y+40,StartPanel.SUBPANEL_BOTTOM_BACKGROUND_COLOR);
        g2.setPaint(gradient);

        //g2.setColor(StartPanel.SUBPANEL_BOTTOM_BACKGROUND_COLOR);//new Color(11, 16, 27, 255));
        g2.fillRoundRect(x, y, w, h, arc, arc);

        g2.setStroke(new BasicStroke(1f));
        g2.setColor(StartPanel.SUBPANEL_OUTLINE_COLOR);
        g2.drawRoundRect(x, y, w, h, arc, arc);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void init(String title, JComponent body) {

        int margin = 15;

        setBorder(new EmptyBorder(margin, margin, margin, margin));

        JLabel titleLabel = new JLabel(title);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 22));
        titleLabel.setForeground(Color.white);

        this.setLayout(new BorderLayout());
        this.add(titleLabel, BorderLayout.NORTH);

        JScrollPane scroll = new JScrollPane(body);
        scroll.setOpaque(false);
        scroll.getViewport().setOpaque(false);
        scroll.setBorder(new EmptyBorder(0,0,0,0));
        this.add(scroll, BorderLayout.CENTER);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
