/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StartSubPanel.java
 *
 * Created on Mar 29, 2011, 12:02:22 AM
 */

package savant.view.swing.start;

import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author mfiume
 */
public class StartSubPanel extends JPanel {

    StartSubPanel(String title, JComponent body) {
         initComponents();
         init(title, body);
    }

    @Override
protected void paintComponent(Graphics g) {

       // g.setColor(new Color(0,0,0,0));
       // g.fillRect(0, 0, this.getWidth(), this.getHeight());

    int x = 2;
    int y = 2;
    int w = getWidth() - 4;
    int h = getHeight() - 4;
    int arc = 30;

    Graphics2D g2 = (Graphics2D) g.create();
    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
            RenderingHints.VALUE_ANTIALIAS_ON);

    GradientPaint gradient = new GradientPaint(x, y-40, StartPanel.subpanelbgcolortop, x, y+40,StartPanel.subpanelbgcolor);
    g2.setPaint(gradient);

    //g2.setColor(StartPanel.subpanelbgcolor);//new Color(11, 16, 27, 255));
    g2.fillRoundRect(x, y, w, h, arc, arc);

    g2.setStroke(new BasicStroke(1f));
    g2.setColor(StartPanel.outlinecolor);
    g2.drawRoundRect(x, y, w, h, arc, arc);

    g2.dispose();
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void init(String title, JComponent body) {

        int margin = 15;

        this.setBorder(new EmptyBorder(margin, margin, margin, margin));

        JLabel titlelabel = new JLabel(title);
        titlelabel.setFont(new Font("Arial", Font.BOLD, 22));
        titlelabel.setForeground(Color.white);

        this.setLayout(new BorderLayout());
        this.add(titlelabel, BorderLayout.NORTH);

        JScrollPane scroll = new JScrollPane(body);
        scroll.setOpaque(false);
        scroll.getViewport().setOpaque(false);
        scroll.setBorder(new EmptyBorder(0,0,0,0));
        this.add(scroll, BorderLayout.CENTER);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
